# Generated by Django 5.0.1 on 2024-02-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.TextField(max_length=50)),
                ('body_part', models.TextField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Exercises',
                'db_table': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setNumber', models.IntegerField()),
                ('setReps', models.IntegerField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('setExercise', models.ManyToManyField(related_name='sets', to='gym.exercise')),
            ],
            options={
                'verbose_name_plural': 'sets',
                'db_table': 'sets',
            },
        ),
    ]
