# Generated by Django 5.0.1 on 2024-02-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sets',
            options={},
        ),
    ]
