# Generated by Django 5.0.1 on 2024-02-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_exercise_options_alter_sets_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(default='basic exercise description', max_length=300),
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.TextField(default='BB', max_length=5),
        ),
    ]
