# Generated by Django 5.0.1 on 2024-02-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_exercise_description_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('BB', 'Barbell'), ('CAB', 'Cable'), ('DB', 'Dumbbell'), ('BW', 'Body Weight')], default='BB', max_length=5),
        ),
    ]
